export {
  ALTAR_SEP,
  MEMORIAL_NOTE_MAX_BYTES,
  MEMORIAL_NOTE_MAX_BYTES_WITH_PARENT,
  MEMORIAL_NOTE_MAX_CHARS,
  MAX_PARENT_RELATIONSHIPS,
  OP_RETURN_SCRIPT_MAX_BYTES,
  altarHasDeathDate,
  altarHonorificLabel,
  altarParentRelationshipLabel,
  altarBareNameFromNote,
  altarSearchRelevance,
  altarSpouseRelationshipLabel,
  altarRelationships,
  birthYearSortKey,
  canAddRelationship,
  normalizeAltarSearchText,
  sortAltarRelationships,
  emptyAltarFields,
  encodeAltarNote,
  encodeDeathDateNote,
  encodeRelationshipNote,
  formatAltarDateInput,
  formatAltarPersonName,
  formatDeathDateInput,
  isAltarPackedNote,
  isDeathDateAmendNote,
  isRelationshipAmendNote,
  linksFromSingularFields,
  memorialDisplayName,
  memorialNoteMaxBytes,
  mergeAltarFields,
  normalizeAltarHonorific,
  normalizeAltarRelatedTxid,
  normalizeAltarRelationshipType,
  parseAltarNote,
  relationshipLinkKey,
  validateAltarFields,
  validateDeathDateFields,
  validateRelationshipFields,
  type AltarFields,
  type AltarHonorific,
  type AltarLocale,
  type AltarRelationshipKind,
  type AltarRelationshipLink,
  type AltarRelationshipType,
  type EncodeAltarNoteOptions,
} from '../../../../src/offering/altarFields.js';
