export {
  ALTAR_SEP,
  MEMORIAL_NOTE_MAX_BYTES,
  MEMORIAL_NOTE_MAX_BYTES_WITH_PARENT,
  MEMORIAL_NOTE_MAX_CHARS,
  MAX_PARENT_RELATIONSHIPS,
  OP_RETURN_SCRIPT_MAX_BYTES,
  altarHasDeathDate,
  altarHonorificLabel,
  altarParentRelationshipLabel,
  altarBareNameFromNote,
  altarSearchRelevance,
  altarSpouseRelationshipLabel,
  altarRelationships,
  birthYearSortKey,
  canAddRelationship,
  normalizeAltarSearchText,
  sortAltarRelationships,
  emptyAltarFields,
  encodeAltarNote,
  encodeDeathDateNote,
  encodeListNote,
  encodeRelationshipNote,
  formatAltarDateInput,
  formatAltarPersonName,
  parseAltarPersonName,
  formatDeathDateInput,
  isAltarPackedNote,
  isDeathDateAmendNote,
  isListAmendNote,
  isRelationshipAmendNote,
  linksFromSingularFields,
  memorialDisplayName,
  memorialNoteMaxBytes,
  mergeAltarFields,
  normalizeAltarHonorific,
  normalizeAltarKind,
  normalizeAltarDateCalendar,
  normalizeAltarListed,
  altarIsEvent,
  altarIsTrendingEligible,
  altarIsCatalogTrendingName,
  altarNotesAreTrendingEligible,
  normalizeAltarRelatedTxid,
  normalizeAltarRelationshipType,
  parseAltarNote,
  prepareDanaNote,
  relationshipLinkKey,
  reofferExtraNote,
  truncateUtf8Bytes,
  utf8ByteLength,
  validateAltarFields,
  validateDeathDateFields,
  validateRelationshipFields,
  type AltarFields,
  type AltarHonorific,
  type AltarKind,
  type AltarDateCalendar,
  type AltarLocale,
  type AltarRelationshipKind,
  type AltarRelationshipLink,
  type AltarRelationshipType,
  type EncodeAltarNoteOptions,
} from '../../../../src/offering/altarFields.js';
